# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 04:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='이름',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='나이',
        ),
        migrations.RemoveField(
            model_name='member',
            name='성별',
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=datetime.datetime(2016, 7, 17, 4, 3, 2, 432756, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(default=datetime.datetime(2016, 7, 17, 4, 3, 17, 277285, tzinfo=utc), max_length=2),
            preserve_default=False,
        ),
    ]
